INSERT INTO CORPORATIONS(NAME) VALUES('CORP1');
INSERT INTO CORPORATIONS(NAME) VALUES('CORP2');
INSERT INTO CORPORATIONS(NAME) VALUES('CORP3');

INSERT INTO USERS(CORPORATION_ID,NAME,AGE) VALUES(1,'USER1',10);
INSERT INTO USERS(CORPORATION_ID,NAME,AGE) VALUES(1,'USER2',20);
INSERT INTO USERS(CORPORATION_ID,NAME,AGE) VALUES(2,'USER3',30);
